apiVersion: v2
appVersion: "1.0"
name: tax-tribunals-application
home: https://github.com/hmcts/tax-tribunals
<<<<<<< HEAD
version: 0.0.23
=======
version: 0.0.22
>>>>>>> 77f23b8 (Bumping chart version/ fixing aliases)
description: Tax Tribunals
dependencies:
  - name: base
    version: 1.0.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: base
    version: 1.0.1
    alias: sidekiq
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: job
    version: 1.0.3
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
