apiVersion: v2
appVersion: "1.0"
# shortened name to avoid hitting 52 character limit for metadata.name being added in templates folder
name: tax-tribs
home: https://github.com/hmcts/tax-tribunals
version: 0.0.13
description: Tax Tribunals
dependencies:
  - name: base
    version: 1.0.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
