base:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    GLIMR_API_CLIENT_MOCK: 'true'

sidekiq:
  # Don't modify below here
  image: ${IMAGE_NAME}

job:
  # Don't modify below here
  image: ${IMAGE_NAME}
