base:
  applicationPort: 8000
  image: "hmctspublic.azurecr.io/tax-tribunals/application"
  ingressHost: tax-tribunals-datacapture.{{ .Values.global.environment }}.platform.hmcts.net
  useWorkloadIdentity: true
  memoryRequests: "2Gi"
  cpuRequests: "500m"
  memoryLimits: "3Gi"
  # set for aat and preview, overridden in flux for other environments
  workloadClientID: "0af403db-e3ab-450b-bcde-884101a065cd"
  environment:
    SECRETS_PATH: "/mnt/secrets/tax-tribunals-cft"
    RAILS_ENV: 'production'
    DB_NAME: taxtribunals
    RAILS_SERVE_STATIC_FILES: 'true'
    DOCKER_STATE: 'migrate'
    NOTIFY_CASE_CONFIRMATION_TEMPLATE_ID: "fa138a1a-5bea-4b01-993f-f25927363d02"
    NOTIFY_FTT_CASE_NOTIFICATION_TEMPLATE_ID: "c2362d14-f99e-4420-b102-8d297dd3a62f"
    NOTIFY_NEW_CASE_SAVED_TEMPLATE_ID: "effca85f-0718-483a-bcd8-529a4e7e6b0f"
    NOTIFY_CHANGE_PASSWORD_TEMPLATE_ID: "cc99c21b-7c28-442e-b8fa-20eba92dec52"
    NOTIFY_RESET_PASSWORD_TEMPLATE_ID: "fcb832bf-a46d-4bf2-a539-b9daa56bbfee"
    NOTIFY_CASE_FIRST_REMINDER_TEMPLATE_ID: "ff66f5ae-6f8c-4365-bb43-a608cbde1e1c"
    NOTIFY_CASE_LAST_REMINDER_TEMPLATE_ID: "23ecd5e1-2a6f-4cbb-9839-d6567360943a"
    NOTIFY_REPORT_PROBLEM_TEMPLATE_ID: "01248de5-4018-4165-8a6f-2508fc481c20"
    NOTIFY_SEND_APPLICATION_DETAIL_TEMPLATE_ID: "aa55e7f3-d26b-411c-bba9-1e3b55815814"
    NOTIFY_SEND_APPLICATION_DETAIL_TEXT_TEMPLATE_ID: "f1f4a25e-9a85-4dd7-9d97-2e3dbd103b38"
    NOTIFY_GLIMR_GENERATION_COMPLETE_ID: "1c3306da-c99a-492a-96a4-c553dc8732de"
    NOTIFY_CASE_CONFIRMATION_CY_TEMPLATE_ID: "ef48c6b6-e3fa-4b1c-8463-9c4fbe504279"
    NOTIFY_FTT_CASE_NOTIFICATION_CY_TEMPLATE_ID: "c2362d14-f99e-4420-b102-8d297dd3a62f"
    NOTIFY_NEW_CASE_SAVED_CY_TEMPLATE_ID: "72008d89-cd28-42f8-8b69-53b4ac27561d"
    NOTIFY_CHANGE_PASSWORD_CY_TEMPLATE_ID: "309c3ac0-3e26-42e2-9a3e-926f66fa3dc2"
    NOTIFY_RESET_PASSWORD_CY_TEMPLATE_ID: "bd60f125-9dc8-4eba-85ca-8059e9dcfe7c"
    NOTIFY_CASE_FIRST_REMINDER_CY_TEMPLATE_ID: "fcddda68-3bcc-4272-85f1-143274a4ae02"
    NOTIFY_CASE_LAST_REMINDER_CY_TEMPLATE_ID: "066415bc-1150-4e51-b506-0c074059cde1"
    NOTIFY_SEND_APPLICATION_DETAIL_CY_TEMPLATE_ID: "be590b09-7371-4f46-8c6e-3393df5faef4"
    NOTIFY_SEND_APPLICATION_DETAIL_TEXT_CY_TEMPLATE_ID: "0654c83d-842c-4464-bdbf-a14160cde0c3"
  keyVaults:
    tax-tribunals-cft:
      secrets:
        - name: secret-key-base
          alias: SECRET_KEY_BASE
        - name: tt-username
          alias: DB_USERNAME
        - name: tt-password
          alias: DB_PASSWORD
        - name: tt-fqdn
          alias: DB_HOST
        - name: redis-url
          alias: REDIS_URL
        - name: external-url
          alias: EXTERNAL_URL
        - name: tax-tribunals-downloader-url
          alias: TAX_TRIBUNALS_DOWNLOADER_URL
        - name: glimr-api-url
          alias: GLIMR_API_URL
        - name: glimr-direct-api-url
          alias: GLIMR_DIRECT_API_URL
        - name: glimr-direct-enabled
          alias: GLIMR_DIRECT_ENABLED
        - name: upload-problems-report-auth-user
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_USER
        - name: upload-problems-report-auth-digest
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_DIGEST
        - name: admin-username
          alias: ADMIN_USERNAME
        - name: admin-password
          alias: ADMIN_PASSWORD
        - name: govuk-notify-api-key
          alias: GOVUK_NOTIFY_API_KEY
        - name: report-problem-email-address
          alias: REPORT_PROBLEM_EMAIL_ADDRESS
        - name: tax-tribunal-email
          alias: TAX_TRIBUNAL_EMAIL
        - name: zendesk-username
          alias: ZENDESK_USERNAME
        - name: zendesk-token
          alias: ZENDESK_TOKEN
        - name: sauce-username
          alias: SAUCE_USERNAME
        - name: sauce-access-key
          alias: SAUCE_ACCESS_KEY
        - name: disable-rack-attack-safelists
          alias: DISABLE_RACK_ATTACK_SAFELISTS
        - name: address-lookup-endpoint
          alias: ADDRESS_LOOKUP_ENDPOINT
        - name: address-lookup-api-key
          alias: ADDRESS_LOOKUP_API_KEY
        - name: address-lookup-api-secret
          alias: ADDRESS_LOOKUP_API_SECRET
        - name: maintenance-enabled
          alias: MAINTENANCE_ENABLED
        - name: maintenance-allowed-ips
          alias: MAINTENANCE_ALLOWED_IPS
        - name: azure-storage-account
          alias: AZURE_STORAGE_ACCOUNT
        - name: azure-storage-key
          alias: AZURE_STORAGE_KEY
        - name: azure-storage-container
          alias: AZURE_STORAGE_CONTAINER
        - name: glimr-authorization-key
          alias: GLIMR_AUTHORIZATION_KEY
        - name: glimr-api-client-mock
          alias: GLIMR_API_CLIENT_MOCK
        - name: sentry-dsn-datacapture
          alias: SENTRY_DSN
        - name: tt-storage-account-primary-access-key
          alias: NEW_AZURE_STORAGE_KEY

redis:
  enabled: false

sidekiq:
  applicationPort: 7433
  readinessPath: /health
  livenessPath: /health
  startupPath: /health
  image: "hmctspublic.azurecr.io/tax-tribunals/application"
  args: [ './sidekiq.sh' ]
  useWorkloadIdentity: true
  memoryRequests: "2Gi"
  cpuRequests: "500m"
  memoryLimits: "3Gi"
  # set for aat and preview, overridden in flux for other environments
  workloadClientID: "0af403db-e3ab-450b-bcde-884101a065cd"
  environment:
    SECRETS_PATH: "/mnt/secrets/tax-tribunals-cft"
    RAILS_ENV: "production"
  keyVaults:
    tax-tribunals-cft:
      secrets:
        - name: secret-key-base
          alias: SECRET_KEY_BASE
        - name: tt-username
          alias: DB_USERNAME
        - name: tt-password
          alias: DB_PASSWORD
        - name: tt-fqdn
          alias: DB_HOST
        - name: tt-instance-id
          alias: DB_NAME
        - name: redis-url
          alias: REDIS_URL
        - name: external-url
          alias: EXTERNAL_URL
        - name: tax-tribunals-downloader-url
          alias: TAX_TRIBUNALS_DOWNLOADER_URL
        - name: glimr-api-url
          alias: GLIMR_API_URL
        - name: glimr-direct-api-url
          alias: GLIMR_DIRECT_API_URL
        - name: glimr-direct-enabled
          alias: GLIMR_DIRECT_ENABLED
        - name: upload-problems-report-auth-user
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_USER
        - name: upload-problems-report-auth-digest
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_DIGEST
        - name: admin-username
          alias: ADMIN_USERNAME
        - name: admin-password
          alias: ADMIN_PASSWORD
        - name: govuk-notify-api-key
          alias: GOVUK_NOTIFY_API_KEY
        - name: report-problem-email-address
          alias: REPORT_PROBLEM_EMAIL_ADDRESS
        - name: tax-tribunal-email
          alias: TAX_TRIBUNAL_EMAIL
        - name: zendesk-username
          alias: ZENDESK_USERNAME
        - name: zendesk-token
          alias: ZENDESK_TOKEN
        - name: sauce-username
          alias: SAUCE_USERNAME
        - name: sauce-access-key
          alias: SAUCE_ACCESS_KEY
        - name: disable-rack-attack-safelists
          alias: DISABLE_RACK_ATTACK_SAFELISTS
        - name: address-lookup-endpoint
          alias: ADDRESS_LOOKUP_ENDPOINT
        - name: address-lookup-api-key
          alias: ADDRESS_LOOKUP_API_KEY
        - name: address-lookup-api-secret
          alias: ADDRESS_LOOKUP_API_SECRET
        - name: maintenance-enabled
          alias: MAINTENANCE_ENABLED
        - name: maintenance-allowed-ips
          alias: MAINTENANCE_ALLOWED_IPS
        - name: azure-storage-account
          alias: AZURE_STORAGE_ACCOUNT
        - name: azure-storage-key
          alias: AZURE_STORAGE_KEY
        - name: azure-storage-container
          alias: AZURE_STORAGE_CONTAINER
        - name: app-insights-instrumentation-key
          alias: APP_INSIGHTS_INSTRUMENTATION_KEY
job:
  image: "hmctspublic.azurecr.io/tax-tribunals/application"
  useWorkloadIdentity: true
  # set for aat and preview, overridden in flux for other environments
  workloadClientID: "0af403db-e3ab-450b-bcde-884101a065cd"
  kind: CronJob
  global:
    jobKind: CronJob
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  ttlSecondsAfterFinished: 216000 # 60 hours
  backoffLimit: 0
  command:
    - "bin/rails"
    - "daily_tasks"
  environment:
    SECRETS_PATH: "/mnt/secrets/tax-tribunals-cft"
    RAILS_ENV: 'production'
    DB_NAME: taxtribunals
  keyVaults:
    tax-tribunals-cft:
      secrets:
        - name: secret-key-base
          alias: SECRET_KEY_BASE
        - name: tt-username
          alias: DB_USERNAME
        - name: tt-password
          alias: DB_PASSWORD
        - name: tt-fqdn
          alias: DB_HOST
        - name: redis-url
          alias: REDIS_URL
        - name: external-url
          alias: EXTERNAL_URL
        - name: tax-tribunals-downloader-url
          alias: TAX_TRIBUNALS_DOWNLOADER_URL
        - name: glimr-api-url
          alias: GLIMR_API_URL
        - name: glimr-direct-api-url
          alias: GLIMR_DIRECT_API_URL
        - name: glimr-direct-enabled
          alias: GLIMR_DIRECT_ENABLED
        - name: upload-problems-report-auth-user
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_USER
        - name: upload-problems-report-auth-digest
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_DIGEST
        - name: admin-username
          alias: ADMIN_USERNAME
        - name: admin-password
          alias: ADMIN_PASSWORD
        - name: govuk-notify-api-key
          alias: GOVUK_NOTIFY_API_KEY
        - name: report-problem-email-address
          alias: REPORT_PROBLEM_EMAIL_ADDRESS
        - name: tax-tribunal-email
          alias: TAX_TRIBUNAL_EMAIL
        - name: zendesk-username
          alias: ZENDESK_USERNAME
        - name: zendesk-token
          alias: ZENDESK_TOKEN
        - name: sauce-username
          alias: SAUCE_USERNAME
        - name: sauce-access-key
          alias: SAUCE_ACCESS_KEY
        - name: disable-rack-attack-safelists
          alias: DISABLE_RACK_ATTACK_SAFELISTS
        - name: address-lookup-endpoint
          alias: ADDRESS_LOOKUP_ENDPOINT
        - name: address-lookup-api-key
          alias: ADDRESS_LOOKUP_API_KEY
        - name: address-lookup-api-secret
          alias: ADDRESS_LOOKUP_API_SECRET
        - name: maintenance-enabled
          alias: MAINTENANCE_ENABLED
        - name: maintenance-allowed-ips
          alias: MAINTENANCE_ALLOWED_IPS
        - name: azure-storage-account
          alias: AZURE_STORAGE_ACCOUNT
        - name: azure-storage-key
          alias: AZURE_STORAGE_KEY
        - name: azure-storage-container
          alias: AZURE_STORAGE_CONTAINER
