base:
  # Don't modify below here
  image: hmctspublic.azurecr.io/tax-tribunals/application:pr-8-9471387-20230912164212
  #image: ${IMAGE_NAME}
  ingressHost: pr-8-tax-tribunals-application.preview.platform.hmcts.net
  workloadClientID: "0af403db-e3ab-450b-bcde-884101a065cd"
