default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tax-tribunals-datacapture_development
test:
  <<: *default
  database: tax-tribunals-datacapture_test

production:
  <<: *default
  database: tax-tribunals-datacapture_production
  username: tax-tribunals-datacapture
  password: <%= ENV['TAX-TRIBUNALS-DATACAPTURE_DATABASE_PASSWORD'] %>
