azure:
  storage_account: <%= ENV['NEW_AZURE_STORAGE_ACCOUNT'] || ENV['AZURE_STORAGE_ACCOUNT'] %>
  storage_container: <%= ENV['NEW_AZURE_STORAGE_CONTAINER'] || ENV['AZURE_STORAGE_CONTAINER'] %>
  new_storage_key: <%= ENV['NEW_AZURE_STORAGE_KEY'] %>

environment:
  name: <%= ENV['ENV_NAME'] || '' %>

