{{- $globals := .Values.global | default dict -}}
{{- $baseValues := dict "Values" .Values.base -}}
{{- $noValues := omit . "Values" -}}
{{- $base := merge $baseValues  $noValues }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hmcts.releasename.v2" $base }}-sidekiq
  labels:
    app.kubernetes.io/name: {{ template "hmcts.releasename.v2" $base }}-sidekiq
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ template "hmcts.releasename.v2" $base }}-sidekiq
    aadpodidbinding: {{ .Values.base.aadIdentityName }}
{{- include "hmcts.annotations.v2" $base | indent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hmcts.releasename.v2" $base }}-sidekiq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "hmcts.releasename.v2" $base }}-sidekiq
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ template "hmcts.releasename.v2" $base }}-sidekiq
        aadpodidbinding: {{ .Values.base.aadIdentityName }}
    {{- (include "hmcts.annotations.v2" $base) | indent 6 }}
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      {{- include "hmcts.interpodantiaffinity.v2" $base | indent 6 }}
      {{- ( include "hmcts.dnsConfig.v2" $base ) | indent 6 }}
      {{- if $globals.enableKeyVaults }}
      volumes:
        - name: vault-c100
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-base-c100
      {{- end }}
      containers:
        - name: sidekiq
          image: {{ .Values.base.image }}
          command: ["./sidekiq.sh", "start"]
          resources:
            requests:
              cpu: 20m
              memory: 500Mi
            limits:
              cpu: 250m
              memory: 4Gi
          ports:
            - containerPort: 7433
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 80
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 80 
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["./sidekiq.sh", "stop"]
          securityContext:
            allowPrivilegeEscalation: false
          {{- ( include "hmcts.secretMounts.v2" $base ) | indent 10 }}
          env:
            - name: GOVUK_NOTIFY_API_KEY
              value: replace_this_at_build_time
            - name: GOVUK_PAY_API_KEY
              value: replace_this_at_build_time
            - name: SECRET_KEY_BASE
              value: replace_this_at_build_time
            #
            # secrets created by `terraform`
            #
            {{ if .Values.redis.url }}
            - name: DATABASE_URL
              value: postgres://{{ .Values.base.postgresql.auth.username}}:{{ .Values.base.postgresql.auth.password}}@{{ .Release.Name }}-postgresql/{{ .Values.base.postgresql.auth.database }}
            - name: REDIS_URL
              value: {{ .Values.redis.url }}
            - name: DATABASE_SSLMODE
              value: 'allow'
            {{ end }}